---
name: Bug Report
description: Report a bug or unexpected behavior
title: "[BUG] "
labels: ["bug", "triage"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Please fill out the form below to help us understand and reproduce the issue.

  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of what the bug is.
      placeholder: "When I click the generate button, the application crashes..."
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What you expected to happen
      placeholder: "The microcourse should generate successfully"
    validations:
      required: true

  - type: dropdown
    id: severity
    attributes:
      label: Severity
      description: How severe is this bug?
      options:
        - Critical (Application crashes, data loss)
        - High (Major functionality broken)
        - Medium (Feature partially broken)
        - Low (Minor inconvenience)
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Version
      description: What version of Tezrisat are you using?
      placeholder: "v1.0.0 or commit hash"
    validations:
      required: false

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Please provide details about your environment
      placeholder: |
        - OS: [e.g., Windows 11, macOS 12.1, Ubuntu 20.04]
        - Browser: [e.g., Chrome 91, Firefox 89]
        - Python version: [e.g., 3.9.7]
        - Node.js version: [e.g., 16.14.0]
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context about the problem here
      placeholder: "Screenshots, error messages, logs, etc."
    validations:
      required: false

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      description: Please confirm the following
      options:
        - label: I have searched for similar issues and confirmed this is not a duplicate
          required: true
        - label: I have tested this on the latest version
          required: false
        - label: I am willing to provide additional information if needed
          required: true