# Generated by Django 4.2.16 on 2025-03-07 20:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Microcourse',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=1000)),
                ('topic', models.CharField(max_length=1000)),
                ('complexity', models.CharField(max_length=1000)),
                ('target_audience', models.CharField(max_length=1000)),
                ('url', models.URLField(blank=True, max_length=500, null=True)),
                ('pdf', models.FileField(blank=True, null=True, upload_to='pdfs/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='microcourses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MicrocourseSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_title', models.TextField(default='Introduction')),
                ('content', models.TextField(default='')),
                ('recall_notes', models.TextField(default='')),
                ('vocabulary', models.TextField(default='')),
                ('quiz', models.TextField(default='')),
                ('code_examples', models.TextField(default='')),
                ('math_expressions', models.TextField(default='')),
                ('microcourse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='api.microcourse')),
            ],
        ),
    ]
