# Generated by Django 4.2.16 on 2025-07-19 01:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_add_subscription_fields'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='stripe_customer_id',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='stripe_subscription_id',
        ),
    ]
