# Generated by Django 4.2.16 on 2025-07-25 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_delete_payment_remove_userprofile_stripe_customer_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='last_reset',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='microcourses_created',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='plan',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='tokens_used',
        ),
    ]
