# Generated by Django 4.2.16 on 2025-07-27 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_userprofile_last_reset_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='encrypted_openai_key',
            field=models.TextField(blank=True, null=True),
        ),
    ]
