# Generated by Django 4.2.16 on 2026-02-07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_make_microcourse_user_optional"),
    ]

    operations = [
        migrations.DeleteModel(
            name="UserProfile",
        ),
    ]
